# -*- coding: utf-8 -*-
"""data Preprocessing : one hot encoding

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NSL3YOqzcm8jH_dsB3--jwswoqJOdl7l
"""

import pandas as pd
df = pd.read_csv("/content/home_prices.csv")
df

df_encoded=pd.get_dummies(df, columns=["locality"], drop_first=True)
df_encoded.sample(5)

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

x = df_encoded.drop('price_lakhs', axis=1)
y = df_encoded['price_lakhs']

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

model=LinearRegression()
model.fit(x_train, y_train)
model.score(x_test, y_test)

x_test

test = pd.DataFrame(
    [
        {'area_sqr_ft':1600	,'bedrooms':2	,'locality_Kollur':False	,'locality_Mankhal':False},
        {'area_sqr_ft': 1600, "bedrooms": 2, "locality_Kollur": False, "locality_Mankhal": True}
])

model.predict(test)