# -*- coding: utf-8 -*-
"""L1 & L2 Regularization

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117RBxj-wX1OySgmn1WBuv-bqU0Gr_h3K
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt

df = pd.read_csv("/content/dataset.csv")
df.head()

X = df.drop(['target'], axis=1)
y = df.target
X.head(3)

y[:5]

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=42)

lm=LinearRegression()
lm.fit(X_train, y_train)
lm.score(X_test, y_test)

lasso_model = Lasso(alpha=1.5)
lasso_model.fit(X_train, y_train)
lasso_model.score(X_test, y_test)

Ridge_model = Ridge(alpha=1.5)
Ridge_model.fit(X_train, y_train)
Ridge_model.score(X_test, y_test)