# -*- coding: utf-8 -*-
"""Linear Regression Single Variable Tutorial code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12vrAUto0WRLTWNcQi0BDJPgEpB085HDU
"""

import pandas as pd

df = pd.read_csv("/content/home_prices.csv")
df.head()

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(df[['area_sqr_ft']], df['price_lakhs'])

model.predict([[1500],[700]])

model.coef_, model.intercept_

model.coef_[0]*1550 + model.intercept_

model.coef_[0]*700 + model.intercept_