# -*- coding: utf-8 -*-
"""Multiple Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-DcgPyx4LvpvjlyD3IAPFDSB6_IMeTe
"""

import pandas as pd
df = pd.read_csv('/content/home_prices.csv')
df.sample(5)

df[['area_sqr_ft','bedrooms']]

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(df[['area_sqr_ft','bedrooms']], df["price_lakhs"])

test = pd.DataFrame([
    {'area_sqr_ft': 1500,  'bedrooms': 2},
    {'area_sqr_ft':2000,  'bedrooms': 3}
])

model.predict(test)

model.coef_, model.intercept_

#y=m1*area + m2*bedroom +b
predicted_price = model.coef_[0]*1500 + model.coef_[1]*2 + model.intercept_
predicted_price